dcConsData = [
	{name:"강풍저격.png", 	keywords:["강풍저격"], 		tags:["랑그", "랑그릿사"]},
	{name:"경멸.gif",		keywords:["경멸"],			tags:["랑그", "랑그릿사"]},
	{name:"고래.gif",		keywords:["고래"],			tags:["랑그", "랑그릿사"]},
	{name:"공주초절.gif",	keywords:["공주초절"],		tags:["랑그", "랑그릿사"]},
	{name:"람다.gif",		keywords:["람다"],			tags:["랑그", "랑그릿사"]},
	{name:"레온고.gif",		keywords:["레온고"],		tags:["랑그", "랑그릿사"]},
	{name:"리아나.gif",		keywords:["리아나"],		tags:["랑그", "랑그릿사"]},
	{name:"맞아.gif",		keywords:["맞아"],			tags:["랑그", "랑그릿사"]},
	{name:"뭐지.png",		keywords:["뭐지"],			tags:["랑그", "랑그릿사"]},
	{name:"미사일.gif",		keywords:["미사일"],		tags:["랑그", "랑그릿사"]},
	{name:"셀붕쿤.png",	keywords:["셀붕쿤"],		tags:["랑그", "랑그릿사"]},
	{name:"시그마.png",	keywords:["시그마"],		tags:["랑그", "랑그릿사"]},
	{name:"시그마펀치.png",	keywords:["시그마펀치"],		tags:["랑그", "랑그릿사"]},
	{name:"신나.gif",		keywords:["신나"],			tags:["랑그", "랑그릿사"]},
	{name:"안녕.png",		keywords:["안녕"],			tags:["랑그", "랑그릿사"]},
	{name:"아니야.gif",		keywords:["아니야"],		tags:["랑그", "랑그릿사"]},
	{name:"어이신입.gif",	keywords:["어이신입"],		tags:["랑그", "랑그릿사"]},
	{name:"유리아.gif",		keywords:["유리아"],		tags:["랑그", "랑그릿사"]},
	{name:"적셔.gif",		keywords:["적셔"],			tags:["랑그", "랑그릿사"]},
	{name:"직감.png",		keywords:["직감"],			tags:["랑그", "랑그릿사"]},
	{name:"젤다칼춤.gif",	keywords:["젤다칼춤"],		tags:["랑그", "랑그릿사"]},
	{name:"천벌.png",		keywords:["천벌"],			tags:["랑그", "랑그릿사"]},
	{name:"통수치기.gif",	keywords:["통수"],			tags:["랑그", "랑그릿사"]},
	{name:"화나.gif",		keywords:["화나"],			tags:["랑그", "랑그릿사"]},
	{name:"힘내.gif",		keywords:["힘내"],			tags:["랑그", "랑그릿사"]},
	{name:"그는신이야.png",	keywords:["그는신이야"],		tags:["랑그", "랑그릿사"]},
	{name:"흠.png",		keywords:["흠"],			tags:["랑그", "랑그릿사"]},
	{name:"레디해요.png",	keywords:["레디해요"],		tags:["랑그", "랑그릿사"]},
	{name:"지켜본다.gif",	keywords:["지켜본다"],		tags:["랑그", "랑그릿사"]},
	{name:"하트.gif",		keywords:["하트"],			tags:["랑그", "랑그릿사"]},
	{name:"헉.gif",		keywords:["헉"],			tags:["랑그", "랑그릿사"]},
	{name:"잘했어요.gif",	keywords:["잘했어요"],		tags:["랑그", "랑그릿사"]},
	{name:"바이.gif",		keywords:["바이"],			tags:["랑그", "랑그릿사"]},
	{name:"개같은.png",	keywords:["개같은"],		tags:["둘리"]},
	{name:"선넘네.png",	keywords:["선넘네"],		tags:["둘리"]},
	{name:"성능.png",		keywords:["성능"],			tags:["둘리"]},
	{name:"아이18.png",	keywords:["아이18"],		tags:["둘리"]},
	{name:"정신.png",		keywords:["정신"],			tags:["둘리"]},
	{name:"죽상.png",		keywords:["죽상"],			tags:["둘리"]},
	{name:"처신.png",		keywords:["처신"],			tags:["둘리"]},
	{name:"호잇.png",		keywords:["호잇"],			tags:["둘리"]},
	{name:"낙원.gif",		keywords:["낙원"],			tags:["야인시대"]},	
	{name:"띠용.gif",		keywords:["띠용"],			tags:["야인시대"]},
	{name:"무릎.gif",		keywords:["무릎"],			tags:["야인시대"]},
	{name:"사딸라.gif",		keywords:["사딸라"],		tags:["야인시대"]},
	{name:"상하이.gif",		keywords:["상하이"],		tags:["야인시대"]},
	{name:"시져시져.gif",	keywords:["시져시져"],		tags:["야인시대"]},
	{name:"안돼1.gif",		keywords:["안돼1"],			tags:["야인시대"]},
	{name:"암.gif",		keywords:["암"],			tags:["야인시대"]},
	{name:"역사적.gif",		keywords:["역사적"],		tags:["야인시대"]},
	{name:"올라잇.gif",		keywords:["올라잇"],		tags:["야인시대"]},
	{name:"의사2.gif",		keywords:["의사2"],			tags:["야인시대"]},
	{name:"일어서.gif",		keywords:["일어서"],		tags:["야인시대"]},
	{name:"탕탕1.gif",		keywords:["탕탕1"],			tags:["야인시대"]},
	{name:"탕탕2.gif",		keywords:["탕탕2"],			tags:["야인시대"]},
	{name:"폭8.gif",		keywords:["폭8"],			tags:["야인시대"]},
	{name:"메강타.gif",		keywords:["메강타"],		tags:["해충"]},
	{name:"가로쉬.png",	keywords:["가로쉬"],		tags:["하스스톤"]},
	{name:"노루.png",		keywords:["노루"],			tags:["하스스톤"]},
	{name:"도적.png",		keywords:["도적"],			tags:["하스스톤"]},
	{name:"씹랄.png",		keywords:["씹랄"],			tags:["하스스톤"]},
	{name:"냥꾼.png",		keywords:["냥꾼"],			tags:["하스스톤"]},
	{name:"법사.png",		keywords:["법사"],			tags:["하스스톤"]},
	{name:"우서.png",		keywords:["우서"],			tags:["하스스톤"]},
	{name:"안두인.png",	keywords:["안두인"],		tags:["하스스톤"]},
	{name:"사적.gif",		keywords:["사적"],			tags:["하스스톤"]},
	{name:"악사.png",		keywords:["악사"],			tags:["하스스톤"]},
	{name:"굴단.png",		keywords:["굴단"],			tags:["하스스톤"]},
	{name:"BB.gif",		keywords:["BB"],			tags:["하스스톤"]},
	{name:"1.png",		keywords:["1"],			tags:["하스스톤"]},
	{name:"사기야.gif",		keywords:["사기야"],		tags:["하스스톤"]},
	{name:"의도.gif",		keywords:["의도"],			tags:["하스스톤"]},
	{name:"철학.gif",		keywords:["철학"],			tags:["하스스톤"]},
	{name:"리시빙.gif",		keywords:["리시빙","니조랄"],		tags:["스타"]},
	{name:"짜잔.gif",		keywords:["짜잔"],			tags:["밈"]},
	{name:"관짝춤.gif",		keywords:["관짝춤"],		tags:["밈"]},
	{name:"가즈아.gif",		keywords:["가즈아"],		tags:["밈"]},
	{name:"가즈아2.gif",	keywords:["가즈아2"],		tags:["밈"]},
	{name:"자빠졌네.gif",	keywords:["지랄하고","자빠졌네"],	tags:["밈"]},
	{name:"아악.gif",		keywords:["아악"],			tags:["밈"]},
	{name:"이마탁.gif",		keywords:["이마탁"],		tags:["밈"]}
];
